services:
  bevman:
    container_name: bevman
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  app:
    container_name: app
    build: 
      context: .
      dockerfile: DockerfileAngular
    ports:
      - 4200:80
